#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xrdp
Version  : 0.9.1
Release  : 3
URL      : https://github.com/neutrinolabs/xrdp/archive/v0.9.1.tar.gz
Source0  : https://github.com/neutrinolabs/xrdp/archive/v0.9.1.tar.gz
Summary  : An open source Remote Desktop Protocol (RDP) server
Group    : Development/Tools
License  : Apache-2.0
Requires: xrdp-bin
Requires: xrdp-config
Requires: xrdp-lib
Requires: xrdp-data
Requires: xrdp-doc
BuildRequires : FreeRDP-dev
BuildRequires : Linux-PAM-dev
BuildRequires : libXfixes-dev
BuildRequires : libXrandr-dev
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(x11)
Patch1: build.patch

%description
xrdp 0.9.1

%package bin
Summary: bin components for the xrdp package.
Group: Binaries
Requires: xrdp-data
Requires: xrdp-config

%description bin
bin components for the xrdp package.


%package config
Summary: config components for the xrdp package.
Group: Default

%description config
config components for the xrdp package.


%package data
Summary: data components for the xrdp package.
Group: Data

%description data
data components for the xrdp package.


%package dev
Summary: dev components for the xrdp package.
Group: Development
Requires: xrdp-lib
Requires: xrdp-bin
Requires: xrdp-data
Provides: xrdp-devel

%description dev
dev components for the xrdp package.


%package doc
Summary: doc components for the xrdp package.
Group: Documentation

%description doc
doc components for the xrdp package.


%package lib
Summary: lib components for the xrdp package.
Group: Libraries
Requires: xrdp-data
Requires: xrdp-config

%description lib
lib components for the xrdp package.


%prep
%setup -q -n xrdp-0.9.1
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=`date +%s -r configure.ac`
%reconfigure --disable-static --sysconfdir=/usr/share/defaults/xrdp
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
## make_install_append content
mv %{buildroot}/usr/share/defaults/xrdp/pam.d %{buildroot}/usr/share
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xrdp
/usr/bin/xrdp-chansrv
/usr/bin/xrdp-dis
/usr/bin/xrdp-genkeymap
/usr/bin/xrdp-keygen
/usr/bin/xrdp-sesadmin
/usr/bin/xrdp-sesman
/usr/bin/xrdp-sesrun
/usr/bin/xrdp-sessvc

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/xrdp-sesman.service
/usr/lib/systemd/system/xrdp.service

%files data
%defattr(-,root,root,-)
/usr/share/defaults/xrdp/xrdp/cert.pem
/usr/share/defaults/xrdp/xrdp/key.pem
/usr/share/defaults/xrdp/xrdp/km-00000407.ini
/usr/share/defaults/xrdp/xrdp/km-00000409.ini
/usr/share/defaults/xrdp/xrdp/km-0000040a.ini
/usr/share/defaults/xrdp/xrdp/km-0000040b.ini
/usr/share/defaults/xrdp/xrdp/km-0000040c.ini
/usr/share/defaults/xrdp/xrdp/km-00000410.ini
/usr/share/defaults/xrdp/xrdp/km-00000411.ini
/usr/share/defaults/xrdp/xrdp/km-00000412.ini
/usr/share/defaults/xrdp/xrdp/km-00000414.ini
/usr/share/defaults/xrdp/xrdp/km-00000415.ini
/usr/share/defaults/xrdp/xrdp/km-00000416.ini
/usr/share/defaults/xrdp/xrdp/km-00000419.ini
/usr/share/defaults/xrdp/xrdp/km-0000041d.ini
/usr/share/defaults/xrdp/xrdp/km-00000807.ini
/usr/share/defaults/xrdp/xrdp/km-00000809.ini
/usr/share/defaults/xrdp/xrdp/km-0000080c.ini
/usr/share/defaults/xrdp/xrdp/km-00000813.ini
/usr/share/defaults/xrdp/xrdp/km-00000816.ini
/usr/share/defaults/xrdp/xrdp/km-0000100c.ini
/usr/share/defaults/xrdp/xrdp/pulse/default.pa
/usr/share/defaults/xrdp/xrdp/rsakeys.ini
/usr/share/defaults/xrdp/xrdp/sesman.ini
/usr/share/defaults/xrdp/xrdp/startwm.sh
/usr/share/defaults/xrdp/xrdp/xrdp.ini
/usr/share/defaults/xrdp/xrdp/xrdp.sh
/usr/share/defaults/xrdp/xrdp/xrdp_keyboard.ini
/usr/share/pam.d/xrdp-sesman
/usr/share/xrdp/ad24b.bmp
/usr/share/xrdp/ad256.bmp
/usr/share/xrdp/cursor0.cur
/usr/share/xrdp/cursor1.cur
/usr/share/xrdp/sans-10.fv1
/usr/share/xrdp/xrdp24b.bmp
/usr/share/xrdp/xrdp256.bmp
/usr/share/xrdp/xrdp_logo.bmp

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/pkgconfig/xrdp.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/xrdp/libcommon.so
/usr/lib64/xrdp/libcommon.so.0
/usr/lib64/xrdp/libcommon.so.0.0.0
/usr/lib64/xrdp/libmc.so
/usr/lib64/xrdp/libmc.so.0
/usr/lib64/xrdp/libmc.so.0.0.0
/usr/lib64/xrdp/librdp.so
/usr/lib64/xrdp/librdp.so.0
/usr/lib64/xrdp/librdp.so.0.0.0
/usr/lib64/xrdp/libscp.so
/usr/lib64/xrdp/libscp.so.0
/usr/lib64/xrdp/libscp.so.0.0.0
/usr/lib64/xrdp/libvnc.so
/usr/lib64/xrdp/libvnc.so.0
/usr/lib64/xrdp/libvnc.so.0.0.0
/usr/lib64/xrdp/libxrdp.so
/usr/lib64/xrdp/libxrdp.so.0
/usr/lib64/xrdp/libxrdp.so.0.0.0
/usr/lib64/xrdp/libxrdpapi.so
/usr/lib64/xrdp/libxrdpapi.so.0
/usr/lib64/xrdp/libxrdpapi.so.0.0.0
/usr/lib64/xrdp/libxup.so
/usr/lib64/xrdp/libxup.so.0
/usr/lib64/xrdp/libxup.so.0.0.0
